### PR TITLE
Merged from upstream Firmata

### PR DESCRIPTION
**Pull request by adamwolf**
@ricklon @EmbeddedMan can you take a look at this PR?  I pulled in the latest from Firmata's master, and merged it into ours.  It should be good, but I can't easily test where I am.

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
So, forgive me for not knowing this, but what's the easiest way to grab all
of the files in their post-merged state so that I can try it out on a real
board?

*Brian

**Comment by adamwolf** [comment]
The wayneandlayne firmata repo is what you want, and is public. If you
check out my repo, that'll do it.  I could zip it up and send to you if
that is easier.

**Comment by EmbeddedMan** [comment]
No no, that's the clue that I needed. Which I guess makes a lot of sense -
you've done your merge and committed the merged files to your W&L repo, and
the PR is against the upstream repo. Cool. I'll test it out here in a sec .
. .

*Brian

**Comment by EmbeddedMan** [comment]
OK, it's quite broke at this point I think. I'm not sure why, yet, but I'm
getting the exact same compile errors that Keith is getting. I'm going to
have to look into it more tonight. Sorry guys!

*Brian

**Comment by adamwolf** [comment]
No problem.  All but 2 things automerged--one was white space, another was
that thing I posted already, and I left ours in.

Lemme know if you need help, git or otherwise.

**Comment by EmbeddedMan** [comment]
Yeah, OK, after comparing what I have on my machine (that I was developing
with when I did the Firmata work) and the merged code from the W&L repo, I
see that they are very different. I'm going to need to work through this
and figure out how to re-apply my changes. Ugg.

From a Git perspective, I have no idea how to manage this. Should I clone
the W&L repo and make changes then issue a PR against it? Or should I clone
Rick's repo and make the changes there?

*Brian

**Comment by EmbeddedMan** [comment]
Please ignore the previous comment - the PR is exactly fine the way it is
right now. I have no idea why I was having trouble with it before, but it
compiles and runs just fine now. Your merge was perfect Adam. Rick, can you
accept the PR and the pass it on up to arduino\firmata?

Thanks guys!

*Brian

**Comment by adamwolf** [comment]
Thanks for taking the time to wrangle this!

**Comment by ricklon** [comment]
I think we need to make sure that the Firmata people. Their Gitter chat is
here:
https://gitter.im/firmata/arduino

On Tue, Aug 4, 2015 at 11:39 PM, Adam Wolf <notifications@github.com> wrote:

> Thanks for taking the time to wrangle this!
>
> On Aug 4, 2015 10:20 PM, "Brian Schmalz" <notifications@github.com> wrote:
>
> > Please ignore the previous comment - the PR is exactly fine the way it is
> > right now. I have no idea why I was having trouble with it before, but it
> > compiles and runs just fine now. Your merge was perfect Adam. Rick, can
> you
> > accept the PR and the pass it on up to arduino\firmata?
> >
> > Thanks guys!
> >
> > *Brian
> >
> > On Tue, Aug 4, 2015 at 10:13 PM, Brian Schmalz <brian@schmalzhaus.com>
> > wrote:
> >
> > > Yeah, OK, after comparing what I have on my machine (that I was
> > developing
> > > with when I did the Firmata work) and the merged code from the W&L
> repo,
> > I
> > > see that they are very different. I'm going to need to work through
> this
> > > and figure out how to re-apply my changes. Ugg.
> > >
> > > From a Git perspective, I have no idea how to manage this. Should I
> clone
> > > the W&L repo and make changes then issue a PR against it? Or should I
> > clone
> > > Rick's repo and make the changes there?
> > >
> > > *Brian
> > >
> > > On Tue, Aug 4, 2015 at 2:28 PM, Adam Wolf <notifications@github.com>
> > > wrote:
> > >
> > >> No problem. All but 2 things automerged--one was white space, another
> > was
> > >> that thing I posted already, and I left ours in.
> > >>
> > >> Lemme know if you need help, git or otherwise.
> > >>
> > >> On Tue, Aug 4, 2015 at 2:23 PM, Brian Schmalz <
> notifications@github.com
> > >
> > >>
> > >> wrote:
> > >>
> > >> > OK, it's quite broke at this point I think. I'm not sure why, yet,
> but
> > >> I'm
> > >> > getting the exact same compile errors that Keith is getting. I'm
> going
> > >> to
> > >> > have to look into it more tonight. Sorry guys!
> > >> >
> > >> > *Brian
> > >> >
> > >> >
> > >> > On Tue, Aug 4, 2015 at 1:18 PM, Brian Schmalz <
> brian@schmalzhaus.com>
> > >> > wrote:
> > >> >
> > >> > > No no, that's the clue that I needed. Which I guess makes a lot of
> > >> sense
> > >> > -
> > >> > > you've done your merge and committed the merged files to your W&L
> > >> repo,
> > >> > and
> > >> > > the PR is against the upstream repo. Cool. I'll test it out here
> in
> > a
> > >> > sec .
> > >> > > . .
> > >> > >
> > >> > > *Brian
> > >> > >
> > >> > > On Tue, Aug 4, 2015 at 1:17 PM, Adam Wolf <
> notifications@github.com
> > >
> > >> > > wrote:
> > >> > >
> > >> > >> The wayneandlayne firmata repo is what you want, and is public.
> If
> > >> you
> > >> > >> check out my repo, that'll do it. I could zip it up and send to
> you
> > >> if
> > >> > >> that is easier.
> > >> > >>
> > >> > >> On Tue, Aug 4, 2015 at 1:01 PM, Brian Schmalz <
> > >> notifications@github.com
> > >> > >
> > >> > >> wrote:
> > >> > >>
> > >> > >> > So, forgive me for not knowing this, but what's the easiest way
> > to
> > >> > grab
> > >> > >> all
> > >> > >> > of the files in their post-merged state so that I can try it
> out
> > >> on a
> > >> > >> real
> > >> > >> > board?
> > >> > >> >
> > >> > >> > *Brian
> > >> > >> >
> > >> > >> > On Tue, Aug 4, 2015 at 12:44 PM, Adam Wolf <
> > >> notifications@github.com>
> > >> > >> > wrote:
> > >> > >> >
> > >> > >> > > @ricklon <https://github.com/ricklon> @EmbeddedMan
> > >> > >> > > <https://github.com/EmbeddedMan> can you take a look at this
> > >> PR? I
> > >> > >> > pulled
> > >> > >> > > in the latest from Firmata's master, and merged it into ours.
> > It
> > >> > >> should
> > >> > >> > be
> > >> > >> > > good, but I can't easily test where I am.
> > >> > >> > > ------------------------------
> > >> > >> > > You can view, comment on, or merge this pull request online
> at:
> > >> > >> > >
> > >> > >> > > https://github.com/ricklon/firmata/pull/2
> > >> > >> > > Commit Summary
> > >> > >> > >
> > >> > >> > > - Fixed off-by-one bug in setFirmwareNameAndVersion() where
> we
> > >> were
> > >> > >> > > writing a zero terminator past the end of the block we'd
> gotten
> > >> from
> > >> > >> > > malloc().
> > >> > >> > > - Merge pull request #184 from EmbeddedMan/master
> > >> > >> > > - fix formatting and bump bugfix version
> > >> > >> > > - prevent analog reporting during system reset
> > >> > >> > > - Merge pull request #186 from firmata/analog-reporting-fix
> > >> > >> > > - update readme
> > >> > >> > > - feat(boards): add support for teensy 3.1
> > >> > >> > > - Merge pull request #192 from mgcrea/master
> > >> > >> > > - bump version
> > >> > >> > > - added experimental StandardFirmataEthernet example
> > >> > >> > > - add ability to use Arduino Yun and ENC28J60-based shields.
> > >> cleaned
> > >> > >> > > up file
> > >> > >> > > - fix UIPEthernet guard constant. add note about needing at
> > >> least 4
> > >> > KB
> > >> > >> > > of SRAM to use UIPEthernt
> > >> > >> > > - removed UIPEthernet option and included Arduino Ethernet by
> > >> > default
> > >> > >> > > - no debugging by default
> > >> > >> > > - fixed Leonardo issue
> > >> > >> > > - moved debug macro to separate file
> > >> > >> > > - apply some changes from StandardFirmataEthernet to
> > >> StandardFirmata
> > >> > >> > > - removed unnecessary code and added D24 to Leonardo ignore
> > list
> > >> > >> > > - moved debug lib and EthernetClientStream to utility folder
> > >> > >> > > - brought StandardFirmataYun up to date with StandardFirmata
> > and
> > >> > added
> > >> > >> > > explanation of sketch purpose
> > >> > >> > > - bump version. update readme and revisions log
> > >> > >> > > - Merge pull request #191 from firmata/ethernet
> > >> > >> > > - added copyright header to boards.h
> > >> > >> > > - added Maxuino to list of Firmata client libraries
> > >> > >> > > - Merged upstream Firmata.
> > >> > >> > > - Merge remote-tracking branch 'ricklonfirmata/master'
> > >> > >> > >
> > >> > >> > > File Changes
> > >> > >> > >
> > >>
>
> > >> > >> > > - *M* Boards.h <
> > >> > >> https://github.com/ricklon/firmata/pull/2/files#diff-0>
> > >> > >> > > (16)
> > >> > >> > > - *M* Firmata.cpp
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-1> (6)
> > >> > >> > > - *M* Firmata.h
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-2> (6)
> > >> > >> > > - *M* examples/StandardFirmata/StandardFirmata.ino
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-3>
> (128)
> > >> > >> > > - *A*
> > >> examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-4>
> (883)
> > >> > >> > > - *M* examples/StandardFirmataYun/StandardFirmataYun.ino
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-5>
> (176)
> > >> > >> > > - *M* extras/revisions.txt
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-6>
> (23)
> > >> > >> > > - *M* library.properties
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-7> (2)
> > >> > >> > > - *M* readme.md
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-8>
> (20)
> > >> > >> > > - *M* release.sh
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-9> (8)
> > >> > >> > > - *A* utility/EthernetClientStream.cpp
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-10>
> > (108)
> > >> > >> > > - *A* utility/EthernetClientStream.h
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-11>
> (52)
> > >> > >> > > - *A* utility/firmataDebug.h
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2/files#diff-12>
> (14)
> > >> > >> > >
> > >> > >> > > Patch Links:
> > >> > >> > >
> > >> > >> > > - https://github.com/ricklon/firmata/pull/2.patch
> > >> > >> > > - https://github.com/ricklon/firmata/pull/2.diff
> > >> > >> > >
> > >> > >> > > —
> > >> > >> > > Reply to this email directly or view it on GitHub
> > >> > >> > > <https://github.com/ricklon/firmata/pull/2>.
> > >> > >> > >
> > >> > >> >
> > >> > >> > —
> > >> > >> > Reply to this email directly or view it on GitHub
> > >> > >> > <
> > https://github.com/ricklon/firmata/pull/2#issuecomment-127693581
> > >> >.
> > >> > >>
> > >> > >> >
> > >> > >>
> > >> > >> —
> > >> > >> Reply to this email directly or view it on GitHub
> > >> > >> <
> https://github.com/ricklon/firmata/pull/2#issuecomment-127698078
> > >.
> > >> > >>
> > >> > >
> > >> > >
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <https://github.com/ricklon/firmata/pull/2#issuecomment-127727772>.
> > >>
> > >> >
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/ricklon/firmata/pull/2#issuecomment-127728876>.
> > >>
> > >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ricklon/firmata/pull/2#issuecomment-127833077>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ricklon/firmata/pull/2#issuecomment-127838139>.
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by EmbeddedMan** [comment]
Rick - sorry, I think part of your message got cut off. We need to make
sure that the Firmata people  . . .  what? Do we need to ask them if we can
send a PR request first?

*Brian

**Comment by ricklon** [comment]
I don't think we need ask them as much as check in. My pull request has
been sitting there for a while.

--Rick

On Wed, Aug 5, 2015 at 11:37 AM, Brian Schmalz <notifications@github.com>
wrote:

> Rick - sorry, I think part of your message got cut off. We need to make
> sure that the Firmata people . . . what? Do we need to ask them if we can
> send a PR request first?
>
> *Brian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ricklon/firmata/pull/2#issuecomment-128042700>.
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by EmbeddedMan** [comment]
I just poked them on Glitter. But it looks like there are conflicts in the
PR on their end (according to https://github.com/firmata/arduino/pull/154 )
I thought we had gotten rid of all of the merge conflicts?

*Brian

**Comment by adamwolf** [comment]
I merged their master branch in, assuming we'd need to merge onto their
master, not dev as I see from the email chain.

I don't think I can do this today, but I could tomorrow, otherwise what you
have to do is add their repository as a new remote, fetch from it, and
merge the newremotename/dev into your working branch.

Lemme know if you need more guidance or if you just want to wait til I can
'git' to it tomorrow, zing.

**Comment by EmbeddedMan** [comment]
Adam, I'm happy to wait for you to do this tomorrow. Thanks!

*Brian

**Comment by ricklon** [comment]
I think the merge was redone to master as they requested. But worth double
checking.

--Rick

On Thu, Aug 6, 2015 at 11:58 AM, Brian Schmalz <notifications@github.com>
wrote:

> Adam, I'm happy to wait for you to do this tomorrow. Thanks!
>
> *Brian
>
>
> On Thu, Aug 6, 2015 at 9:54 AM, Adam Wolf <notifications@github.com>
> wrote:
>
> > I merged their master branch in, assuming we'd need to merge onto their
> > master, not dev as I see from the email chain.
> >
> > I don't think I can do this today, but I could tomorrow, otherwise what
> you
> > have to do is add their repository as a new remote, fetch from it, and
> > merge the newremotename/dev into your working branch.
> >
> > Lemme know if you need more guidance or if you just want to wait til I
> can
> > 'git' to it tomorrow, zing.
> >
> > On Aug 6, 2015 8:52 AM, "Brian Schmalz" <notifications@github.com>
> wrote:
> >
> > > I just poked them on Glitter. But it looks like there are conflicts in
> > the
> > > PR on their end (according to
> > https://github.com/firmata/arduino/pull/154
> > > )
> > > I thought we had gotten rid of all of the merge conflicts?
> > >
> > > *Brian
> > >
> > > On Wed, Aug 5, 2015 at 10:25 AM, Ricklon <notifications@github.com>
> > wrote:
> > >
> > > > I think we need to make sure that the Firmata people. Their Gitter
> chat
> > > is
> > > > here:
> > > > https://gitter.im/firmata/arduino
> > > >
> > > > On Tue, Aug 4, 2015 at 11:39 PM, Adam Wolf <notifications@github.com
> >
> > > > wrote:
> > > >
> > > > > Thanks for taking the time to wrangle this!
> > > > >
> > > > > On Aug 4, 2015 10:20 PM, "Brian Schmalz" <notifications@github.com
> >
> > > > wrote:
> > > > >
> > > > > > Please ignore the previous comment - the PR is exactly fine the
> way
> > > it
> > > > is
> > > > > > right now. I have no idea why I was having trouble with it
> before,
> > > but
> > > > it
> > > > > > compiles and runs just fine now. Your merge was perfect Adam.
> Rick,
> > > can
> > > > > you
> > > > > > accept the PR and the pass it on up to arduino\firmata?
> > > > > >
> > > > > > Thanks guys!
> > > > > >
> > > > > > *Brian
> > > > > >
> > > > > > On Tue, Aug 4, 2015 at 10:13 PM, Brian Schmalz <
> > > brian@schmalzhaus.com>
> > > > > > wrote:
> > > > > >
> > > > > > > Yeah, OK, after comparing what I have on my machine (that I was
> > > > > > developing
> > > > > > > with when I did the Firmata work) and the merged code from the
> > W&L
> > > > > repo,
> > > > > > I
> > > > > > > see that they are very different. I'm going to need to work
> > through
> > > > > this
> > > > > > > and figure out how to re-apply my changes. Ugg.
> > > > > > >
> > > > > > > From a Git perspective, I have no idea how to manage this.
> > Should I
> > > > > clone
> > > > > > > the W&L repo and make changes then issue a PR against it? Or
> > > should I
> > > > > > clone
> > > > > > > Rick's repo and make the changes there?
> > > > > > >
> > > > > > > *Brian
> > > > > > >
> > > > > > > On Tue, Aug 4, 2015 at 2:28 PM, Adam Wolf <
> > > notifications@github.com>
> > > > > > > wrote:
> > > > > > >
> > > > > > >> No problem. All but 2 things automerged--one was white space,
> > > > another
> > > > > > was
> > > > > > >> that thing I posted already, and I left ours in.
> > > > > > >>
> > > > > > >> Lemme know if you need help, git or otherwise.
> > > > > > >>
> > > > > > >> On Tue, Aug 4, 2015 at 2:23 PM, Brian Schmalz <
> > > > > notifications@github.com
> > > > > > >
> > > > > > >>
> > > > > > >> wrote:
> > > > > > >>
> > > > > > >> > OK, it's quite broke at this point I think. I'm not sure
> why,
> > > yet,
> > > > > but
> > > > > > >> I'm
> > > > > > >> > getting the exact same compile errors that Keith is getting.
> > I'm
> > > > > going
> > > > > > >> to
> > > > > > >> > have to look into it more tonight. Sorry guys!
> > > > > > >> >
> > > > > > >> > *Brian
> > > > > > >> >
> > > > > > >> >
> > > > > > >> > On Tue, Aug 4, 2015 at 1:18 PM, Brian Schmalz <
> > > > > brian@schmalzhaus.com>
> > > > > > >> > wrote:
> > > > > > >> >
> > > > > > >> > > No no, that's the clue that I needed. Which I guess makes
> a
> > > lot
> > > > of
> > > > > > >> sense
> > > > > > >> > -
> > > > > > >> > > you've done your merge and committed the merged files to
> > your
> > > > W&L
> > > > > > >> repo,
> > > > > > >> > and
> > > > > > >> > > the PR is against the upstream repo. Cool. I'll test it
> out
> > > here
> > > > > in
> > > > > > a
> > > > > > >> > sec .
> > > > > > >> > > . .
> > > > > > >> > >
> > > > > > >> > > *Brian
> > > > > > >> > >
> > > > > > >> > > On Tue, Aug 4, 2015 at 1:17 PM, Adam Wolf <
> > > > > notifications@github.com
> > > > > > >
> > > > > > >> > > wrote:
> > > > > > >> > >
> > > > > > >> > >> The wayneandlayne firmata repo is what you want, and is
> > > public.
> > > > > If
> > > > > > >> you
> > > > > > >> > >> check out my repo, that'll do it. I could zip it up and
> > send
> > > to
> > > > > you
> > > > > > >> if
> > > > > > >> > >> that is easier.
> > > > > > >> > >>
> > > > > > >> > >> On Tue, Aug 4, 2015 at 1:01 PM, Brian Schmalz <
> > > > > > >> notifications@github.com
> > > > > > >> > >
> > > > > > >> > >> wrote:
> > > > > > >> > >>
> > > > > > >> > >> > So, forgive me for not knowing this, but what's the
> > easiest
> > > > way
> > > > > > to
> > > > > > >> > grab
> > > > > > >> > >> all
> > > > > > >> > >> > of the files in their post-merged state so that I can
> try
> > > it
> > > > > out
> > > > > > >> on a
> > > > > > >> > >> real
> > > > > > >> > >> > board?
> > > > > > >> > >> >
> > > > > > >> > >> > *Brian
> > > > > > >> > >> >
> > > > > > >> > >> > On Tue, Aug 4, 2015 at 12:44 PM, Adam Wolf <
> > > > > > >> notifications@github.com>
> > > > > > >> > >> > wrote:
> > > > > > >> > >> >
> > > > > > >> > >> > > @ricklon <https://github.com/ricklon> @EmbeddedMan
> > > > > > >> > >> > > <https://github.com/EmbeddedMan> can you take a look
> > at
> > > > this
> > > > > > >> PR? I
> > > > > > >> > >> > pulled
> > > > > > >> > >> > > in the latest from Firmata's master, and merged it
> into
> > > > ours.
> > > > > > It
> > > > > > >> > >> should
> > > > > > >> > >> > be
> > > > > > >> > >> > > good, but I can't easily test where I am.
> > > > > > >> > >> > > ------------------------------
> > > > > > >> > >> > > You can view, comment on, or merge this pull request
> > > online
> > > > > at:
> > > > > > >> > >> > >
> > > > > > >> > >> > > https://github.com/ricklon/firmata/pull/2
> > > > > > >> > >> > > Commit Summary
> > > > > > >> > >> > >
> > > > > > >> > >> > > - Fixed off-by-one bug in setFirmwareNameAndVersion()
> > > where
> > > > > we
> > > > > > >> were
> > > > > > >> > >> > > writing a zero terminator past the end of the block
> > we'd
> > > > > gotten
> > > > > > >> from
> > > > > > >> > >> > > malloc().
> > > > > > >> > >> > > - Merge pull request #184 from EmbeddedMan/master
> > > > > > >> > >> > > - fix formatting and bump bugfix version
> > > > > > >> > >> > > - prevent analog reporting during system reset
> > > > > > >> > >> > > - Merge pull request #186 from
> > > firmata/analog-reporting-fix
> > > > > > >> > >> > > - update readme
> > > > > > >> > >> > > - feat(boards): add support for teensy 3.1
> > > > > > >> > >> > > - Merge pull request #192 from mgcrea/master
> > > > > > >> > >> > > - bump version
> > > > > > >> > >> > > - added experimental StandardFirmataEthernet example
> > > > > > >> > >> > > - add ability to use Arduino Yun and ENC28J60-based
> > > > shields.
> > > > > > >> cleaned
> > > > > > >> > >> > > up file
> > > > > > >> > >> > > - fix UIPEthernet guard constant. add note about
> > needing
> > > at
> > > > > > >> least 4
> > > > > > >> > KB
> > > > > > >> > >> > > of SRAM to use UIPEthernt
> > > > > > >> > >> > > - removed UIPEthernet option and included Arduino
> > > Ethernet
> > > > by
> > > > > > >> > default
> > > > > > >> > >> > > - no debugging by default
> > > > > > >> > >> > > - fixed Leonardo issue
> > > > > > >> > >> > > - moved debug macro to separate file
> > > > > > >> > >> > > - apply some changes from StandardFirmataEthernet to
> > > > > > >> StandardFirmata
> > > > > > >> > >> > > - removed unnecessary code and added D24 to Leonardo
> > > ignore
> > > > > > list
> > > > > > >> > >> > > - moved debug lib and EthernetClientStream to utility
> > > > folder
> > > > > > >> > >> > > - brought StandardFirmataYun up to date with
> > > > StandardFirmata
> > > > > > and
> > > > > > >> > added
> > > > > > >> > >> > > explanation of sketch purpose
> > > > > > >> > >> > > - bump version. update readme and revisions log
> > > > > > >> > >> > > - Merge pull request #191 from firmata/ethernet
> > > > > > >> > >> > > - added copyright header to boards.h
> > > > > > >> > >> > > - added Maxuino to list of Firmata client libraries
> > > > > > >> > >> > > - Merged upstream Firmata.
> > > > > > >> > >> > > - Merge remote-tracking branch
> 'ricklonfirmata/master'
> > > > > > >> > >> > >
> > > > > > >> > >> > > File Changes
> > > > > > >> > >> > >
> > > > > > >>
> > > > >
>
> > > > > > >> > >> > > - *M* Boards.h <
> > > > > > >> > >> https://github.com/ricklon/firmata/pull/2/files#diff-0>
> > > > > > >> > >> > > (16)
> > > > > > >> > >> > > - *M* Firmata.cpp
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-1>
> > > > (6)
> > > > > > >> > >> > > - *M* Firmata.h
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-2>
> > > > (6)
> > > > > > >> > >> > > - *M* examples/StandardFirmata/StandardFirmata.ino
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-3>
> > > > > (128)
> > > > > > >> > >> > > - *A*
> > > > > > >> examples/StandardFirmataEthernet/StandardFirmataEthernet.ino
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-4>
> > > > > (883)
> > > > > > >> > >> > > - *M*
> > examples/StandardFirmataYun/StandardFirmataYun.ino
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-5>
> > > > > (176)
> > > > > > >> > >> > > - *M* extras/revisions.txt
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-6>
> > > > > (23)
> > > > > > >> > >> > > - *M* library.properties
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-7>
> > > > (2)
> > > > > > >> > >> > > - *M* readme.md
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-8>
> > > > > (20)
> > > > > > >> > >> > > - *M* release.sh
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-9>
> > > > (8)
> > > > > > >> > >> > > - *A* utility/EthernetClientStream.cpp
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-10
> > > >
> > > > > > (108)
> > > > > > >> > >> > > - *A* utility/EthernetClientStream.h
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-11
> > > >
> > > > > (52)
> > > > > > >> > >> > > - *A* utility/firmataDebug.h
> > > > > > >> > >> > > <
> > https://github.com/ricklon/firmata/pull/2/files#diff-12
> > > >
> > > > > (14)
> > > > > > >> > >> > >
> > > > > > >> > >> > > Patch Links:
> > > > > > >> > >> > >
> > > > > > >> > >> > > - https://github.com/ricklon/firmata/pull/2.patch
> > > > > > >> > >> > > - https://github.com/ricklon/firmata/pull/2.diff
> > > > > > >> > >> > >
> > > > > > >> > >> > > —
> > > > > > >> > >> > > Reply to this email directly or view it on GitHub
> > > > > > >> > >> > > <https://github.com/ricklon/firmata/pull/2>.
> > > > > > >> > >> > >
> > > > > > >> > >> >
> > > > > > >> > >> > —
> > > > > > >> > >> > Reply to this email directly or view it on GitHub
> > > > > > >> > >> > <
> > > > > > https://github.com/ricklon/firmata/pull/2#issuecomment-127693581
> > > > > > >> >.
> > > > > > >> > >>
> > > > > > >> > >> >
> > > > > > >> > >>
> > > > > > >> > >> —
> > > > > > >> > >> Reply to this email directly or view it on GitHub
> > > > > > >> > >> <
> > > > > https://github.com/ricklon/firmata/pull/2#issuecomment-127698078
> > > > > > >.
> > > > > > >> > >>
> > > > > > >> > >
> > > > > > >> > >
> > > > > > >> >
> > > > > > >> > —
> > > > > > >> > Reply to this email directly or view it on GitHub
> > > > > > >> > <
> > > https://github.com/ricklon/firmata/pull/2#issuecomment-127727772
> > > > >.
> > > > > > >>
> > > > > > >> >
> > > > > > >>
> > > > > > >> —
> > > > > > >> Reply to this email directly or view it on GitHub
> > > > > > >> <
> > https://github.com/ricklon/firmata/pull/2#issuecomment-127728876
> > > >.
> > > > > > >>
> > > > > > >
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> https://github.com/ricklon/firmata/pull/2#issuecomment-127833077
> > >.
> > > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/ricklon/firmata/pull/2#issuecomment-127838139
> >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Co-founder
> > > > Fair Use Building and Research (FUBAR) Labs
> > > > http://fubarlabs.org
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/ricklon/firmata/pull/2#issuecomment-128036584>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ricklon/firmata/pull/2#issuecomment-128372111>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ricklon/firmata/pull/2#issuecomment-128402681>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ricklon/firmata/pull/2#issuecomment-128418230>.
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by EmbeddedMan** [comment]
So here's the reply from the Firmata guys.Looks like we have more work to
do before we can have our changes accepted.

someone needs to rebase that branch before it can be merged. It's way
behind master. Also we need to talk about how to better incorporate Servo
support for chipKIT in StandardFirmata.

**Comment by EmbeddedMan** [comment]
OK, so I had a nice chat with the Firmata guys on Glitter today. We're
going to drop the current PR, as we need to integrate Keith's latest
changes and they want some things to be different too. No problem.

When I asked how they wanted it done, I got this response:
"yeah create a topic branch and submit a pull request against master"

So, does this mean they want me to clone firmata/arduino, create a new
local branch off of the master branch, make my changes, commit my changes
to my clone of firmata/arduino, then submit a PR between my new branch and
their master branch? (I didn't know you could cross branches with a PR like
that - is that how it's supposed to work?)

I'm just trying to get the expected flow right here before I make a fool of
myself.

*Brian

**Comment by ricklon** [comment]
Good question. I think your interpretation is correct. You can pull from any branch. I wasn't sure the details so I found a short explanation here:
http://stackoverflow.com/questions/1709177/git-pull-certain-branch-from-github

I

**Pull request merged**
